:asset_root: public
:load_path:
  - app/javascripts
  - vendor/sprockets/*/src
  - vendor/plugins/*/javascripts
  - vendor/plugins/*/app/javascripts
:source_files:
  - app/javascripts/jquery.simplemodal-1.3.4.min.js
  - app/javascripts/jquery.form
  - app/javascripts/jquery.address-1.1.min.js
  - app/javascripts/bk.*.js
