:asset_root: public
:load_path:
  - app/javascripts
  - vendor/sprockets/*/src
  - vendor/plugins/*/javascripts
  - vendor/plugins/*/app/javascripts
:source_files:
  - app/javascripts/jquery.*.js
  - app/javascripts/bk.core.js
  - app/javascripts/bk.*.js
